# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.19.0
clone:
  depth: full
    
pipelines:
  default:  
    - parallel:
      - step:
          name: Deploy SPA
          caches:
            - node
          script:
            - cd SPA
            - npm install
            - npm build
            #- npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
            #- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
            - cd ..
            - git subtree push --prefix=SPA https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_SPA_NAME.git master
      - step:
          name: Deploy MetadataRede
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - cd metadatarede
            - npm install
            - npm test
            - cd ..
            - git subtree push --prefix=metadatarede https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
